version: "3"
services:
  cbpro:
    build: ./cbpro-trader
    command: python3 ./cbpro-trader.py
  web:
    build: ./cbpro-trader/web
    command: bash -c "npm install && npm start"
    volumes:
      - ./cbpro-trader/web/:/frontend/